# Generated by Django 5.2.8 on 2025-11-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_subject_badge_streak_question_subject_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, help_text='Brief topic/description shown in the app', max_length=300),
        ),
    ]
